accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views


from .views import (homepage_view, dashboard_view, logout_request, update_profile_view,
                    manage_instagram_links_view, update_company_info_view, company_info_view, login_or_register_view,
                    ResetPasswordView

                    )

from .action_views import (validate_category_creation_view, validate_link_creation_view, edit_category_view,
                           edit_link_view, delete_category_or_link_view, validate_company_create_product_or_service_view,
                           validate_login_form_view, validate_register_form_view,
                           validate_company_create_image_view, update_company_image_view, delete_company_image_view
                           )
from .admin_view import ManageSubsView

app_name = 'accounts'

urlpatterns = [

    path('admin/manage-subs/', ManageSubsView.as_view(), name='manageSubsView'),

    path('homepage/', homepage_view, name='homepage_view'),
    path('register/', login_or_register_view, name='register'),
    path('logout/', logout_request, name='logout'),

    path('dashboard/', dashboard_view, name='dashboard_view'),
    path('update-profile/', update_profile_view, name='update-profile'),
    path('manage-instagram/<str:slug>/', manage_instagram_links_view, name='manage_links'),
    path('update-company-info/<str:slug>/', company_info_view, name='update_company_info'),
    path('update-company/<int:pk>/', update_company_info_view, name='update_company_data'),

    path('action/create/link/<str:slug>/', validate_link_creation_view, name='validate_create_link'),
    path('action/create/category/<str:slug>/', validate_category_creation_view, name='validate_create_category'),
    path('action/edit/link/<int:pk>/', edit_link_view, name='edit_link'),
    path('action/edit/category/<int:pk>/', edit_category_view, name='edit_category'),
    path('action/delete/<str:action>/<int:pk>/', delete_category_or_link_view, name='delete_link_or_category'),
    path('action/validate/create-product-or-service/<str:slug>/<slug:action>/',
         validate_company_create_product_or_service_view,
         name='validate_product_or_service'
         ),

    path('action/validate/login/', validate_login_form_view, name='validate_login'),
    path('action/validate/register/', validate_register_form_view, name='validate_register'),

    path('action/validate-company-create-image/<str:slug>/', validate_company_create_image_view, name='create_company_image'),
    path('action/update-company-image/<int:pk>/', update_company_image_view, name='update_company_image'),
    path('action/delete-company-image/<int:pk>/', delete_company_image_view, name='delete_company_image'),


    # passwords resets etc
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='auth_templates/change_password.html'),
         name='change_password'),






]

monemvasia_portal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),

    path('accounts/', include('accounts.urls')),
    path('αγγελιες/', include('jobPostings.urls')),
    path('catalogue/', include('catalogue.urls')),
    path('company/', include('companies.urlpatterns')),
    path('newsletter/', include('newsletters.urls')),


    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='auth_templates/reset/password_reset_form.html'),
         name='password_forgot'),
    path('reset-password-done/', auth_views.PasswordResetDoneView.as_view(template_name='auth_templates/reset/password_reset_done.html'), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-done/', auth_views.PasswordResetDoneView.as_view(), name='reset_done')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
User = get_user_model()

from companies.models import Company


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    taxes_id = models.CharField(unique=True, max_length=20, verbose_name='ΑΦΜ')
    name = models.CharField(max_length=200, blank=True, verbose_name='ΟΝΟΜΑΤΕΠΩΝΥΜΟ')
    phone = models.CharField(max_length=50, blank=True, verbose_name='ΤΗΛΕΦΩΝΟ')
    notes = models.TextField(blank=True)
    permission_grand = models.BooleanField(default=False, verbose_name='ΕΠΙΒΑΙΒΑΙΩΣΗ')
    monthly_cost = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    def __str__(self):
        return self.user.username


class InstagramCategories(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ')

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('accounts:edit_category', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('accounts:delete_link_or_category', kwargs={'action': 'category', 'pk': self.id})


class InstagramLink(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    category = models.ForeignKey(InstagramCategories, on_delete=models.CASCADE, related_name='my_links', verbose_name='ΚΑΤΗΓΟΡΙΑ')
    title = models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ')
    url = models.URLField()

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('accounts:edit_link', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('accounts:delete_link_or_category', kwargs={'action': 'link', 'pk': self.id})

companies/models.py
from django.db import models
from django.db.models import Q, Sum
from django.shortcuts import reverse
from django.contrib.auth import get_user_model

import datetime
from tinymce.models import HTMLField
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
from tinymce.models import HTMLField

from .managers import CompanyManager, ServiceManager
from frontend.models import City


User = get_user_model()

BUSINESS_TYPE = (
        ('1', 'ΕΜΠΟΡΙΟ'),
        ('2', 'ΕΣΤΙΑΣΗ'),
        ('3', 'ΥΠΗΡΕΣΙΕΣ'),
        ('4', 'ΜΕΙΚΤΟ')
    )


def upload_to(instance, filename):
    return f'/companies/images/{instance.id}/{filename}'


def upload_image(instance, filename):
    return f'/companies/images/{instance.company.id}/{filename}'


def upload_logo(instance, filename):
    return f'/companies/logos/{instance.company.id}/{filename}'


def upload_services(instance, filename):
    return f'/companies/services/{instance.company.id}/{filename}'


PAYMENT_METHODS = [
    ('a', 'ΤΡΑΠΕΖΑ ΠΕΙΡΑΙΩΣ'),
    ('b', 'ΕΘΝΙΚΗ ΤΡΑΠΕΖΑ'),
    ('c', 'ΜΕΤΡΗΤΑ'),
]

PRIORITY_OPTIONS = (
        ('1', 'ΠΛΑΝΟ ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 50/ΜΗΝΑ'),
        ('2', 'ΠΛΑΝΟ ΓΙΑ ΥΠΗΡΕΣΙΕΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 35/ΜΗΝΑ'),
    )


class CategoryForCompany(MPTTModel):
    name = models.CharField(max_length=220)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='childrens', verbose_name='Κατηγορία')
    image = models.ImageField(upload_to='companies/categories/', blank=True, null=True)
    big_image = models.ImageField(upload_to='companies/catalogue/upload-big-images/', blank=True, null=True)
    text = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)

    class Meta:
        verbose_name_plural = '5. ΚΑΤΗΓΟΡΙΕΣ ΕΤΑΙΡΙΩΝ'
        verbose_name = 'ΚΑΤΗΓΟΡΙΑ ΕΤΑΙΡΙΑΣ'

    def front_name(self):
        full_path = [f'- {self.name}']
        k = self.parent
        while k is not None:
            space_sym = "&nbsp" * 4
            full_path.append(space_sym)
            k = k.parent
        return ''.join(full_path[::-1])

    def is_parent(self):
        return False if self.childrens.exists() else True

    def get_absolute_url(self):
        return reverse('product_category', kwargs={'slug': self.slug})

    def get_childrens(self):
        childrens = self.childrens.filter(active=True).order_by('order')
        return childrens


class CompanyCategory(models.Model):
    title = models.CharField(max_length=220)
    image = models.ImageField(upload_to='companies/categories/', blank=True, null=True)
    big_image = models.ImageField(upload_to='companies/catalogue/upload-big-images/', blank=True, null=True)
    text = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL, related_name='childrens')

    class Meta:
        verbose_name_plural = '5. ΚΑΤΗΓΟΡΙΕΣ ΕΤΑΙΡΙΩΝ'
        verbose_name = 'ΚΑΤΗΓΟΡΙΑ ΕΤΑΙΡΙΑΣ'


    def __str__(self):
        return self.title

    def is_parent(self):
        return True if self.have_childrens() else False

    def get_absolute_url(self):
        if self.is_parent():
            return reverse('category_parent_list_view', kwargs={'slug': self.slug})
        else:
            return reverse('category', kwargs={'slug': self.slug})

    def have_childrens(self):
        return self.childrens.exists()

    def tag_image(self):
        return self.image.url if self.image else ''

    def tag_big_image(self):
        return self.big_image.url if self.big_image else ''


class Company(models.Model):
    admin_active = models.BooleanField(default=False, verbose_name='ΓΕΝΙΚΟΣ ΔΙΑΚΟΠΤΗΣ')
    business_type = models.CharField(choices=BUSINESS_TYPE, default='1', max_length=1)
    featured = models.BooleanField(default=False)
    first_choice = models.BooleanField(default=False, verbose_name='ΠΡΟΤΕΡΙΟΤΗΤΑ')
    category = models.ManyToManyField(CompanyCategory, null=True, blank=True, related_name='my_companies')
    categories = models.ManyToManyField(CategoryForCompany, null=True, blank=True, related_name='company')
    status = models.BooleanField(default=False, verbose_name='ΚΑΤΑΣΤΑΣΗ')
    subscription_ends = models.DateField(null=True)
    priority = models.CharField(max_length=1, choices=PRIORITY_OPTIONS, default='3')
    item_support = models.BooleanField(default=False)
    max_items = models.IntegerField(default=6)
    title = models.CharField(max_length=200)
    city = models.ForeignKey(City, blank=True, null=True, on_delete=models.SET_NULL)
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='companies')
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    google_map_location = models.TextField()
    extra_css = models.TextField(null=True, blank=True)

    # page_relates_fields
    service_title = models.CharField(max_length=220, default='ΥΠΗΡΕΣΙΕΣ')

    my_query = CompanyManager()
    objects = models.Manager()

    counter = models.IntegerField(default=0)
    value = models.DecimalField(decimal_places=2, max_digits=20, default=0, verbose_name='ΥΠΟΛΟΙΠΟ')

    class Meta:
        ordering = ['featured', 'first_choice', 'priority',]
        verbose_name_plural = '1. ΕΠΙΧΕΙΡΗΣΕΙΣ'
        
    def save(self, *args, **kwargs):
        if self.admin_active:
            self.status = True if self.subscription_ends >= datetime.datetime.now().date() else False
        else:
            self.status = False
        self.item_support = True if self.max_items > 0 else False
        orders = self.orders.aggregate(Sum('value'))['value__sum'] if self.orders.exists() else 0
        payments = self.payments.aggregate(Sum('value'))['value__sum'] if self.payments.exists() else 0
        self.value = orders - payments
        self.counter = self.hits.count()
        super(Company, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('company_view', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('accounts:update_company_info', kwargs={'slug': self.slug})

    def support_products(self):
        return True if self.business_type in ['1', '4'] else False

    def support_service(self)-> bool:
        return True if self.business_type in ['3', '4'] else False

    def sub_value(self):
        return 20 if self.business_type == '3' else 40 if self.business_type == '2' else 100

    def get_background_image(self):
        qs = self.images.filter(background_img=True)
        return qs.first().image.url if qs.exists() else None

    def rest_photos(self):
        return self.images.filter(background_img=False)

    @staticmethod
    def filter_data(request, qs):
        q = request.GET.get('q', None)
        if q:
            qs = qs.filter(Q(title__icontains=q) |
                           Q(city__title__icontains=q)
                           )
        return qs


class CompanyHitCounter(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='hits')
    session = models.CharField(max_length=220)

    def save(self, *args, **kwargs):
        super(CompanyHitCounter, self).save(*args, **kwargs)
        self.company.save()

    def __str__(self):
        return self.company

    @staticmethod
    def update_hit(request, company):
        if not request.session.exists(request.session.session_key):
            request.session.create()
        session = request.session.session_key
        qs = CompanyHitCounter.objects.filter(company=company, session=session)
        if qs.exists():
            last_obj = qs.last()
            diff = datetime.datetime.today() - last_obj.timestamp.replace(tzinfo=None)
            if diff.days > 1:
                CompanyHitCounter.objects.create(
                    company=company,
                    session=session
                )
        else:
            CompanyHitCounter.objects.create(
                company=company,
                session=session
            )


class CompanyInformation(models.Model):
    is_visible = models.BooleanField(default=True)
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name='detail')
    logo_image = models.ImageField(blank=True, upload_to='companies/logos/', help_text='lOGO ΣΤΗΝ ΣΕΛΙΔΑ ΤΟΥ ΠΕΛΑΤΗ 120*40')
    logo_site = models.ImageField(blank=True, null=True, upload_to='companies/logo_site/', help_text='LOGO ΣΤΗΝ ΔΙΚΗ ΜΑΣ ΣΕΛΙΔΑ 400*600')
    address = models.CharField(blank=True, verbose_name='ΔΙΕΥΘΥΝΣΗ', max_length=220)
    phone = models.CharField(max_length=20, blank=True, verbose_name='ΤΗΛΕΦΩΝΟ')
    cellphone = models.CharField(max_length=20, blank=True, verbose_name='ΚΙΝΗΤΟ')
    website = models.URLField(blank=True)
    email = models.EmailField(blank=True, null=True)
    description = HTMLField(blank=True, null=True, verbose_name='ΠΕΡΙΓΡΑΦΗ')
    facebook_url = models.URLField(blank=True, null=True, verbose_name='ΣΕΛΙΔΑ FACEBOOK')
    instagram_url = models.URLField(blank=True, null=True, verbose_name='ΣΕΛΙΔΑ INSTAGRAM')

    class Meta:
        verbose_name_plural = '2. ΠΡΟΦΙΛ ΕΠΙΧΕΙΡΗΣΕΩΝ'

    def __str__(self):
        return self.company.title

    def full_phones(self):
        phones = self.cellphone if self.cellphone else ''
        phones += f' | {self.phone}' if self.phone else '.'
        return phones

    def full_address(self):
        return f'{self.address} | {self.company.city}'

    def tag_image(self):
        return self.logo_site.url if self.logo_site else ' '

    def tag_logo(self):
        return self.logo_image.url if self.logo_image else ' '

    def show_products(self):

contact/models.py
from django.db import models

# Create your models here.

from companies.models import PRIORITY_OPTIONS

class Contact(models.Model):
    CHOICES = (
        ('a', 'ΓΕΝΙΚΗ ΕΡΩΤΗΣΗ'),
        ('b', 'ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ')
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    category = models.CharField(choices=CHOICES, max_length=1, default='a', verbose_name='ΚΑΤΗΓΟΡΙΑ')
    email = models.EmailField()
    title = models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ')
    text = models.TextField(verbose_name='ΠΕΡΙΓΡΑΦΗ')

    def __str__(self):
        return f'{self.email}'


class BusinessContact(models.Model):


    is_readed = models.BooleanField(default=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=200, verbose_name='ΟΝΟΜΑΤΕΠΩΝΥΜΟ')
    title = models.CharField(max_length=200, verbose_name='ONOMA ΕΤΑΙΡΙΑΣ')
    phone = models.CharField(max_length=15, verbose_name='ΤΗΛΕΦΩΝΟ ΕΠΙΚΟΙΝΩΝΙΑΣ')
    afm = models.CharField(max_length=10, verbose_name='ΑΦΜ', unique=True)
    priority = models.CharField(max_length=1, choices=PRIORITY_OPTIONS,
                                default='3', verbose_name='ΠΛΑΝΟ')
    city = models.CharField(max_length=150, verbose_name='ΠΟΛΗ')

    class Meta:
        verbose_name_plural = 'ΕΓΓΡΑΦΕΣ ΕΠΙΧΕΙΡΗΣΕΩΝ'

    def __str__(self):
        return self.name

accounts/templates/auth_templates/change_password.html
{% extends 'index.html' %}

{% block content %}
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>{{ page_title }}</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'homepage' %}">ΑΡΧΙΚΗ ΣΕΛΙΔΑ</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ page_title }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin: 2%">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4>ΑΛΛΑΓΗ ΚΩΔΙΚΟΥ</h4>
                </div>
                <div class="card-body">
                    <form class="form" method="post" action="{% url 'accounts:validate_login' %}">
                        {% csrf_token %}
                        {{ form }}
                        <br> <hr>
                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> ΑΠΟΘΗΚΕΥΣΗ</button>
                    </form>
                </div>
            </div>

        </div>
        <div class="col-6">
            <a href="{% url 'accounts:dashboard_view' %}" class="btn btn-warning">ΕΠΙΣΤΡΟΦΗ</a>
        </div>
    </div>

{% endblock %}

accounts/templates/auth_templates/dashboard_.html
{% extends 'index.html' %}


{% block content %}
    <div role="main" class="main">

        <div class="row">
            <section class="page-header page-header-modern bg-color-light-scale-1 page-header-md">
         <div class="container">
             <div class="row">
                 <div class="col-md-12 align-self-center p-static order-2 text-center">
                     <h1 class="text-dark font-weight-bold text-8">{{ category }}</h1>
                     <br />
                 </div>
                 <div class="col-md-12 align-self-center order-1">
                     <ul class="breadcrumb d-block text-center">
                         <li><a href="{% url 'homepage' %}">Αρχικη Σελιδα</a></li>
                         <li class="active">{{ category }}</li>
                     </ul>
                 </div>
             </div>
         </div>
     </section>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4>ΠΛΗΡΟΦΟΡΙΕΣ</h4>
                        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">ΑΠΟΣΥΝΔΕΣΗ</a>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item ">EMAIL: {{ user.username }} </li>
                            <li class="list-group-item">ΟΝΟΜΑΤΕΠΩΝΥΜΟ:{{ user.profile.name }}</li>
                            <li class="list-group-item">ΑΦΜ: {{ user.profile.taxes_id }}</li>
                            <li class="list-group-item">ΤΗΛΕΦΩΝΟ:{{ user.profile.phone }}</li>

                        </ul>
                        <br>
                        <hr>
                        <a href="{% url 'accounts:update-profile' %}" class="btn btn-danger">ΑΛΛΑΓΗ ΣΤΟΙΧΕΙΩΝ</a>
                        <a href="" class="btn btn-danger pull-right">ΑΛΛΑΓΗ PASSWORD</a>


                    </div>
                </div>
            </div>
            <div class="col-6">
                <h4>ΕΤΑΙΡΙΕΣ</h4>
                <div class="card">
                    <div class="card-header">
                        <h5>ΣΤΟΙΧΕΙΑ ΓΙΑ ΔΗΜΙΟΥΡΓΙΑ ΝΕΑΣ ΕΙΣΑΓΩΓΗΣ</h5>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-success" role="alert">
                            <h4 class="alert-heading">ΤΙΤΛΟΣ ΕΤΑΙΡΙΑΣ | EMAIL</h4>
                            <p>ΦΩΤΟΓΡΑΦΙΕΣ: LOGO IMAGE('718*982') | BACKGROUND_IMAGE(1970*550)</p>
                            <hr>
                            <p class="mb-0">
                                ΔΙΕΥΘΥΝΣΗ | ΤΗΛΕΦΩΝΟ | ΚΙΝΗΤΟ | WEBSITE | FACEBOOK PAGE - INSTAGRAM PAGE
                            </p>
                        </div>
                    </div>
                </div>

                {% for company in user.companies.all %}
                    <div class="card" style="margin-bottom: 3%">
                        <div class="card-body">
                            <h5 class="card-title">{{ company.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                Κατηγορια: {{ company.get_business_type_display }}
                                <br>
                            </h6>
                            <hr/>
                            <p class="card-text">
                                Πλάνο: {{ company.get_priority_display }}
                                <br />
                                 ΠΡΟΤΕΙΝΟΜΕΝΗ: {{ company.featured }}
                                <br>
                                ΜΕΓΙΣΤΗ ΠΟΣΟΤΗΤΑ ΠΡΟΪΌΝΤΩΝ/ΥΠΗΡΕΣΙΩΝ: {{ company.max_items }}
                                <br>

                                <span style="color:red">Λήξη Συνδρομής: {{ company.subscription_ends }}</span>
                            </p>
                            <a href="{{ company.get_edit_url }}" class="card-link">ΕΠΕΞΕΡΓΑΣΙΑ ΕΤΑΙΡΙΑΣ</a>
                            <a target="_blank" href="{{ company.get_absolute_url }}" class="card-link">ΠΛΗΡΟΦΟΡΙΕΣ</a>
                            <a href="{% url 'accounts:manage_links' company.slug %}" class="card-link">Link Tree</a>
                            <!-- Button trigger modal -->

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">ΠΛΑΝΑ ΕΠΙΧΕΙΡΗΣΕΩΝ</h1>
            <p class="lead">ΠΑΡΕΧΕΤΕ Η ΔΥΝΑΤΟΤΗΤΑ ΕΠΕΞΕΡΓΑΣΙΑΣ ΤΩΝ ΠΡΟΪΟΝΤΩΝ ΑΠΟ ΕΜΑΣ ΜΕ ΕΠΙΠΛΕΟΝ ΚΟΣΤΟΣ 10 € τα 6 ή 2 € το ένα, σε όλα τα προγράμματα</p>
        </div>
        <div class="row" style="margin: 3%">
            <div class="card col-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">ΒΑΣΙΚΟ</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">€ 20<small class="text-muted">/ μήνα</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>6 προϊόντα</li>
                  <li>Link Tree (INSTAGRAM FEED)</li>
                  <li>1 Campaign Διαφήμισης</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">6 ΜΗΝΕΣ: € 100</button>
              </div>
            </div>
            <div class="card col-4 box-shadow">
              <div style="background-color: dodgerblue" class="card-header">
                <h4  class="my-0 font-weight-normal">ΕΠΑΓΓΕΛΜΑΤΙΚΟ (ΠΡΟΤΕΙΝΟΜΕΝΟ)</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">€ 40 <small class="text-muted">/ μήνα</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                  <li>20 προϊόντα</li>
                  <li>Link Tree (INSTAGRAM FEED)</li>
                  <li>2 Campaign Διαφήμισης</li>
                  <li>ΠΡΟΤΕΡΑΙΌΤΗΤΑ ΣΕ 2 ΠΡΟΪΟΝΤΑ ΣΑΣ</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">6 ΜΗΝΕΣ: € 200</button>
              </div>
            </div>
            <div class="card col-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">ΠΡΟΧΩΡΗΜΕΝΟ</h4>
              </div>
              <div class="card-body">
                <h1 class="card-title pricing-card-title">€ 100<small class="text-muted">/ μήνα</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>30 προϊόντα</li>
                    <li>Link Tree (INSTAGRAM FEED)</li>
                    <li>4 Campaign Διαφήμισης</li>
                    <li>ΔΙΑΧΕΙΡΙΣΗ SOCIAL MEDIA</li>
                    <li>ΠΡΟΤΕΡΑΙΌΤΗΤΑ ΣΕ 5 ΠΡΟΪΟΝΤΑ ΣΑΣ</li>
                </ul>
                <<button type="button" class="btn btn-lg btn-block btn-outline-primary">6 ΜΗΝΕΣ: € 500</button>
              </div>
            </div>


        </div>

{% endblock %}

{% block extra_js %}
    <script>
        $('#modalN').click(function (evt) {
            $('#exampleModal').show()
        })
    </script>
{% endblock %}

accounts/templates/auth_templates/deny_access.html
{% extends 'index.html' %}

{% block content %}

    <div class="row">
        <div style="margin: 4%" class="col-12">
            <h4>Παρακαλώ περιμένετε να επιβεβεώσουν τα στοιχεία σας οι διαχειριστές. </h4>
        </div>
    </div>
{% endblock %}