accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views


from .views import (homepage_view, dashboard_view, logout_request, update_profile_view,
                    manage_instagram_links_view, update_company_info_view, company_info_view, login_or_register_view,
                    ResetPasswordView

                    )

from .action_views import (validate_category_creation_view, validate_link_creation_view, edit_category_view,
                           edit_link_view, delete_category_or_link_view, validate_company_create_product_or_service_view,
                           validate_login_form_view, validate_register_form_view,
                           validate_company_create_image_view, update_company_image_view, delete_company_image_view
                           )
from .admin_view import ManageSubsView

app_name = 'accounts'

urlpatterns = [

    path('admin/manage-subs/', ManageSubsView.as_view(), name='manageSubsView'),

    path('homepage/', homepage_view, name='homepage_view'),
    path('register/', login_or_register_view, name='register'),
    path('logout/', logout_request, name='logout'),

    path('dashboard/', dashboard_view, name='dashboard_view'),
    path('update-profile/', update_profile_view, name='update-profile'),
    path('manage-instagram/<str:slug>/', manage_instagram_links_view, name='manage_links'),
    path('update-company-info/<str:slug>/', company_info_view, name='update_company_info'),
    path('update-company/<int:pk>/', update_company_info_view, name='update_company_data'),

    path('action/create/link/<str:slug>/', validate_link_creation_view, name='validate_create_link'),
    path('action/create/category/<str:slug>/', validate_category_creation_view, name='validate_create_category'),
    path('action/edit/link/<int:pk>/', edit_link_view, name='edit_link'),
    path('action/edit/category/<int:pk>/', edit_category_view, name='edit_category'),
    path('action/delete/<str:action>/<int:pk>/', delete_category_or_link_view, name='delete_link_or_category'),
    path('action/validate/create-product-or-service/<str:slug>/<slug:action>/',
         validate_company_create_product_or_service_view,
         name='validate_product_or_service'
         ),

    path('action/validate/login/', validate_login_form_view, name='validate_login'),
    path('action/validate/register/', validate_register_form_view, name='validate_register'),

    path('action/validate-company-create-image/<str:slug>/', validate_company_create_image_view, name='create_company_image'),
    path('action/update-company-image/<int:pk>/', update_company_image_view, name='update_company_image'),
    path('action/delete-company-image/<int:pk>/', delete_company_image_view, name='delete_company_image'),


    # passwords resets etc
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='auth_templates/change_password.html'),
         name='change_password'),






]

frontend/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (HomepageView, ArticleDetailView, CategoryListView, ContactView, SearchPageView,
                    CompanyDetailView, CityListView, CityDetailView, link_page_view, ProductListView, ServiceListView,
                    CategoryParentListView
                    )

from .action_views import (create_new_item_view, create_new_service_view, validate_edit_form_info_view,
                           edit_delete_product_view,edit_or_delete_service_view
                           )

from .ajax_views import ajax_product_modal_view, ajax_service_modal_view
from .footer_views import cookies_policy_view, term_of_use_view

from catalogue.views import CategoryDetailView

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),

    path('επιχειρηση/<str:slug>/', CompanyDetailView.as_view(), name='company_view'),

    path('category/<str:slug>/', CategoryListView.as_view(), name='category'),
    path('search/', SearchPageView.as_view(), name='search'),
    path('article/<str:slug>/', ArticleDetailView.as_view(), name='article'),
    path('contact/', ContactView.as_view(), name='contact'),

    path('καττηγορία/<str:slug>/', CategoryParentListView.as_view(), name='category_parent_list_view'),
    path('προϊοντα/', ProductListView.as_view(), name='product_list_view'),
    path('υπηρεσιες/', ServiceListView.as_view(), name='service_list_view'),
    path('προιοντα/κατηγοριες/', ProductListView.as_view(), name='product_categories'), # maybe will get deleted
    path('προιοντα/κατηγορια/<str:slug>/', CategoryDetailView.as_view(), name='product_category'),


    path('πολεις/', CityListView.as_view(), name='cities'),
    path('πολη/<str:slug>/', CityDetailView.as_view(), name='city_detail'),


    path('link/<str:slug>/', link_page_view, name='link_page'),

    # action views
    path('action/create-service/<str:slug>/', create_new_service_view, name='create_service_view'),
    path('action/create-item/<str:slug>/', create_new_item_view, name='create_item_view'),
    path('action/edit-info/<str:slug>/', validate_edit_form_info_view, name='validate_company_info'),
    path('action/edit-service/<int:pk>/<str:action>/', edit_or_delete_service_view, name='edit_or_delete_service_view'),
    path('action/edit-product/<int:pk>/<str:action>/', edit_delete_product_view, name='edit_or_delete_item_view'),


    # ajax
    path('ajax/product-modal/<str:slug>/', ajax_product_modal_view, name='ajax_product_modal'),
    path('ajax/service-modal/<str:slug>/', ajax_service_modal_view, name='ajax_service_modal'),


    path('privacy', cookies_policy_view, name='privacy'),
    path('term-of-use', term_of_use_view, name='term_of_use')

]

monemvasia_portal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),

    path('accounts/', include('accounts.urls')),
    path('αγγελιες/', include('jobPostings.urls')),
    path('catalogue/', include('catalogue.urls')),
    path('company/', include('companies.urlpatterns')),
    path('newsletter/', include('newsletters.urls')),


    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='auth_templates/reset/password_reset_form.html'),
         name='password_forgot'),
    path('reset-password-done/', auth_views.PasswordResetDoneView.as_view(template_name='auth_templates/reset/password_reset_done.html'), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-done/', auth_views.PasswordResetDoneView.as_view(), name='reset_done')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

companies/models.py
from django.db import models
from django.db.models import Q, Sum
from django.shortcuts import reverse
from django.contrib.auth import get_user_model

import datetime
from tinymce.models import HTMLField
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
from tinymce.models import HTMLField

from .managers import CompanyManager, ServiceManager
from frontend.models import City


User = get_user_model()

BUSINESS_TYPE = (
        ('1', 'ΕΜΠΟΡΙΟ'),
        ('2', 'ΕΣΤΙΑΣΗ'),
        ('3', 'ΥΠΗΡΕΣΙΕΣ'),
        ('4', 'ΜΕΙΚΤΟ')
    )


def upload_to(instance, filename):
    return f'/companies/images/{instance.id}/{filename}'


def upload_image(instance, filename):
    return f'/companies/images/{instance.company.id}/{filename}'


def upload_logo(instance, filename):
    return f'/companies/logos/{instance.company.id}/{filename}'


def upload_services(instance, filename):
    return f'/companies/services/{instance.company.id}/{filename}'


PAYMENT_METHODS = [
    ('a', 'ΤΡΑΠΕΖΑ ΠΕΙΡΑΙΩΣ'),
    ('b', 'ΕΘΝΙΚΗ ΤΡΑΠΕΖΑ'),
    ('c', 'ΜΕΤΡΗΤΑ'),
]

PRIORITY_OPTIONS = (
        ('1', 'ΠΛΑΝΟ ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 50/ΜΗΝΑ'),
        ('2', 'ΠΛΑΝΟ ΓΙΑ ΥΠΗΡΕΣΙΕΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 35/ΜΗΝΑ'),
    )


class CategoryForCompany(MPTTModel):
    name = models.CharField(max_length=220)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                            related_name='childrens', verbose_name='Κατηγορία')
    image = models.ImageField(upload_to='companies/categories/', blank=True, null=True)
    big_image = models.ImageField(upload_to='companies/catalogue/upload-big-images/', blank=True, null=True)
    text = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)

    class Meta:
        verbose_name_plural = '5. ΚΑΤΗΓΟΡΙΕΣ ΕΤΑΙΡΙΩΝ'
        verbose_name = 'ΚΑΤΗΓΟΡΙΑ ΕΤΑΙΡΙΑΣ'

    def front_name(self):
        full_path = [f'- {self.name}']
        k = self.parent
        while k is not None:
            space_sym = "&nbsp" * 4
            full_path.append(space_sym)
            k = k.parent
        return ''.join(full_path[::-1])

    def is_parent(self):
        return False if self.childrens.exists() else True

    def get_absolute_url(self):
        return reverse('product_category', kwargs={'slug': self.slug})

    def get_childrens(self):
        childrens = self.childrens.filter(active=True).order_by('order')
        return childrens


class CompanyCategory(models.Model):
    title = models.CharField(max_length=220)
    image = models.ImageField(upload_to='companies/categories/', blank=True, null=True)
    big_image = models.ImageField(upload_to='companies/catalogue/upload-big-images/', blank=True, null=True)
    text = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL, related_name='childrens')

    class Meta:
        verbose_name_plural = '5. ΚΑΤΗΓΟΡΙΕΣ ΕΤΑΙΡΙΩΝ'
        verbose_name = 'ΚΑΤΗΓΟΡΙΑ ΕΤΑΙΡΙΑΣ'


    def __str__(self):
        return self.title

    def is_parent(self):
        return True if self.have_childrens() else False

    def get_absolute_url(self):
        if self.is_parent():
            return reverse('category_parent_list_view', kwargs={'slug': self.slug})
        else:
            return reverse('category', kwargs={'slug': self.slug})

    def have_childrens(self):
        return self.childrens.exists()

    def tag_image(self):
        return self.image.url if self.image else ''

    def tag_big_image(self):
        return self.big_image.url if self.big_image else ''


class Company(models.Model):
    admin_active = models.BooleanField(default=False, verbose_name='ΓΕΝΙΚΟΣ ΔΙΑΚΟΠΤΗΣ')
    business_type = models.CharField(choices=BUSINESS_TYPE, default='1', max_length=1)
    featured = models.BooleanField(default=False)
    first_choice = models.BooleanField(default=False, verbose_name='ΠΡΟΤΕΡΙΟΤΗΤΑ')
    category = models.ManyToManyField(CompanyCategory, null=True, blank=True, related_name='my_companies')
    categories = models.ManyToManyField(CategoryForCompany, null=True, blank=True, related_name='company')
    status = models.BooleanField(default=False, verbose_name='ΚΑΤΑΣΤΑΣΗ')
    subscription_ends = models.DateField(null=True)
    priority = models.CharField(max_length=1, choices=PRIORITY_OPTIONS, default='3')
    item_support = models.BooleanField(default=False)
    max_items = models.IntegerField(default=6)
    title = models.CharField(max_length=200)
    city = models.ForeignKey(City, blank=True, null=True, on_delete=models.SET_NULL)
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='companies')
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    google_map_location = models.TextField()
    extra_css = models.TextField(null=True, blank=True)

    # page_relates_fields
    service_title = models.CharField(max_length=220, default='ΥΠΗΡΕΣΙΕΣ')

    my_query = CompanyManager()
    objects = models.Manager()

    counter = models.IntegerField(default=0)
    value = models.DecimalField(decimal_places=2, max_digits=20, default=0, verbose_name='ΥΠΟΛΟΙΠΟ')

    class Meta:
        ordering = ['featured', 'first_choice', 'priority',]
        verbose_name_plural = '1. ΕΠΙΧΕΙΡΗΣΕΙΣ'
        
    def save(self, *args, **kwargs):
        if self.admin_active:
            self.status = True if self.subscription_ends >= datetime.datetime.now().date() else False
        else:
            self.status = False
        self.item_support = True if self.max_items > 0 else False
        orders = self.orders.aggregate(Sum('value'))['value__sum'] if self.orders.exists() else 0
        payments = self.payments.aggregate(Sum('value'))['value__sum'] if self.payments.exists() else 0
        self.value = orders - payments
        self.counter = self.hits.count()
        super(Company, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('company_view', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('accounts:update_company_info', kwargs={'slug': self.slug})

    def support_products(self):
        return True if self.business_type in ['1', '4'] else False

    def support_service(self)-> bool:
        return True if self.business_type in ['3', '4'] else False

    def sub_value(self):
        return 20 if self.business_type == '3' else 40 if self.business_type == '2' else 100

    def get_background_image(self):
        qs = self.images.filter(background_img=True)
        return qs.first().image.url if qs.exists() else None

    def rest_photos(self):
        return self.images.filter(background_img=False)

    @staticmethod
    def filter_data(request, qs):
        q = request.GET.get('q', None)
        if q:
            qs = qs.filter(Q(title__icontains=q) |
                           Q(city__title__icontains=q)
                           )
        return qs


class CompanyHitCounter(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='hits')
    session = models.CharField(max_length=220)

    def save(self, *args, **kwargs):
        super(CompanyHitCounter, self).save(*args, **kwargs)
        self.company.save()

    def __str__(self):
        return self.company

    @staticmethod
    def update_hit(request, company):
        if not request.session.exists(request.session.session_key):
            request.session.create()
        session = request.session.session_key
        qs = CompanyHitCounter.objects.filter(company=company, session=session)
        if qs.exists():
            last_obj = qs.last()
            diff = datetime.datetime.today() - last_obj.timestamp.replace(tzinfo=None)
            if diff.days > 1:
                CompanyHitCounter.objects.create(
                    company=company,
                    session=session
                )
        else:
            CompanyHitCounter.objects.create(
                company=company,
                session=session
            )


class CompanyInformation(models.Model):
    is_visible = models.BooleanField(default=True)
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name='detail')
    logo_image = models.ImageField(blank=True, upload_to='companies/logos/', help_text='lOGO ΣΤΗΝ ΣΕΛΙΔΑ ΤΟΥ ΠΕΛΑΤΗ 120*40')
    logo_site = models.ImageField(blank=True, null=True, upload_to='companies/logo_site/', help_text='LOGO ΣΤΗΝ ΔΙΚΗ ΜΑΣ ΣΕΛΙΔΑ 400*600')
    address = models.CharField(blank=True, verbose_name='ΔΙΕΥΘΥΝΣΗ', max_length=220)
    phone = models.CharField(max_length=20, blank=True, verbose_name='ΤΗΛΕΦΩΝΟ')
    cellphone = models.CharField(max_length=20, blank=True, verbose_name='ΚΙΝΗΤΟ')
    website = models.URLField(blank=True)
    email = models.EmailField(blank=True, null=True)
    description = HTMLField(blank=True, null=True, verbose_name='ΠΕΡΙΓΡΑΦΗ')
    facebook_url = models.URLField(blank=True, null=True, verbose_name='ΣΕΛΙΔΑ FACEBOOK')
    instagram_url = models.URLField(blank=True, null=True, verbose_name='ΣΕΛΙΔΑ INSTAGRAM')

    class Meta:
        verbose_name_plural = '2. ΠΡΟΦΙΛ ΕΠΙΧΕΙΡΗΣΕΩΝ'

    def __str__(self):
        return self.company.title

    def full_phones(self):
        phones = self.cellphone if self.cellphone else ''
        phones += f' | {self.phone}' if self.phone else '.'
        return phones

    def full_address(self):
        return f'{self.address} | {self.company.city}'

    def tag_image(self):
        return self.logo_site.url if self.logo_site else ' '

    def tag_logo(self):
        return self.logo_image.url if self.logo_image else ' '

    def show_products(self):

frontend/templates/include/category_card.html
{% load static %}

<div class="product-box">
    <div class="img-wrapper">
        {% comment %}
        <div class="lable-block">
            <span class="lable3">new</span>
            <span class="lable4">on sale</span>
        </div>
        {% endcomment %}
        <div class="front">
            <a  href="{{ category.get_absolute_url }}">
                <img
                    src="{{ category.tag_image }}"
                    class="img-fluid blur-up lazyload bg-img " alt="">
            </a>
        </div>
        <div class="back">
            <a  href="{{ category.get_absolute_url }}"><img
                    src="{{ category.tag_image }}"
                    class="img-fluid blur-up lazyload bg-img" alt="">
            </a>
        </div>
        <div class="cart-info cart-wrap">

        </div>
    </div>
    <div class="product-detail">
        <div class="rating">

        </div>
        <a  href="{{ category.get_absolute_url }}">
            <h6>{{ category }}</h6>
        </a>


    </div>
</div>

frontend/templates/include/city_card.html
{% load static %}

<div class="product-box">
    <div class="img-wrapper">
        <div class="front">
            <a href="{{ city.get_absolute_url }}">
                <img
                    src="{{ city.tag_image }}"
                    class="img-fluid blur-up lazyload bg-img" alt=""
                >
            </a>
        </div>
        <div class="back">
            <a href="{{ city.get_absolute_url }}"><img
                    src="{{ city.tag_image }}"
                    class="img-fluid blur-up lazyload bg-img" alt="">
            </a>
        </div>
        <div class="cart-info cart-wrap">

        </div>
    </div>
    <div class="product-detail">
        <hr/>
        <a href="{{ city.get_absolute_url }}">
            <h4>{{ city }}</h4>
        </a>
        <hr />
    </div>
</div>

frontend/templates/include/company_card.html
{% load static %}

<div class="product-box">
    <div class="img-wrapper">
        <div class="front">
            <a href="{{ company.get_absolute_url }}">
                <img
                    src="{{ company.detail.tag_image }}"
                    class="img-fluid blur-up lazyload bg-img" alt=""
                >
            </a>
        </div>
        <div class="back">
            <a href="{{  company.get_absolute_url }}"><img
                    src="{{ company.detail.tag_image }}"
                    class="img-fluid blur-up lazyload bg-img" alt="">
            </a>
        </div>
        <div class="cart-info cart-wrap">

        </div>
    </div>
    <div class="product-detail">
        <hr/>
        <div class="rating">
            {{ company.get_business_type_display }}
        </div>
        <a href="{{  company.get_absolute_url }}">
            <h4>{{ company }}</h4>
        </a>
        <hr />
        <p>{{ company.city }}</p>
    </div>
</div>

frontend/templates/include/head.html
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="multikart">
    <meta name="keywords" content="multikart">
    <meta name="author" content="multikart">
    <link rel="icon" href="{% static 'my_assets/favicon.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'my_assets/favicon.png' %}" type="image/x-icon">
    <title>ΜΟΝΕΜΒΑΣΙΑ | {{ page_title }}</title>

    {% include 'include/css.html' %}
    <style>

        input{
            width: 100%;
        }
    </style>

        <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-8CWJ8HD64S"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-8CWJ8HD64S');
    </script>

</head>

frontend/templates/include/navbar.html
{% load static %}

 <!-- header start -->
<header>
    <div class="mobile-fix-option"></div>
    <div class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="header-contact">
                        <ul>
                            <li>Καλώς ήρθατε στο monemvasia.org</li>
                            <li><i class="fa fa-phone" aria-hidden="true"></i>Email: monemvasia.org@gmail.com</li>
                        </ul>
                    </div>
                </div>
                    <div class="col-lg-6 text-end">
                        <ul class="header-dropdown">

                            <li class="onhover-dropdown mobile-account"> <i class="fa fa-user" aria-hidden="true"></i>
                                ΠΕΡΙΟΧΗ ΠΕΛΑΤΩΝ
                                <ul class="onhover-show-div">
                                   {% if request.user.is_authenticated %}
                                        <li><a href="{% url 'accounts:homepage_view' %}">ΔΙΑΧΕΙΡΙΣΗ</a></li> 
                                    {% else %}
                                        <li><a href="{% url 'accounts:homepage_view' %}">ΣΥΝΔΕΣΗ</a></li>
                                     {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="main-menu">
                        <div class="menu-left">
                            <div class="navbar">
                                <a href="javascript:void(0)" onclick="openNav()">
                                    <div class="bar-style"><i class="fa fa-bars sidebar-bar" aria-hidden="true"></i>
                                    </div>
                                </a>
                                <div id="mySidenav" class="sidenav">
                                    <a href="javascript:void(0)" class="sidebar-overlay" onclick="closeNav()"></a>
                                    <nav>
                                        <div onclick="closeNav()">
                                            <div class="sidebar-back text-start"><i class="fa fa-angle-left pe-2"
                                                    aria-hidden="true"></i> Back</div>
                                        </div>
                                        <ul id="sub-menu" class="sm pixelstrap sm-vertical">

                                            <li><a href="#">Facebook</a></li>
                                            <li><a href="#">Instagram</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="brand-logo">
                                <a href="{% url 'homepage' %}"><img width="193" height="40" src="{% static 'my_assets/photos/mo_po.jpg' %}"
                                        class="img-fluid blur-up lazyload" alt=""></a>
                            </div>
                        </div>
                        <div class="menu-right pull-right">
                            <div>
                                <nav id="main-nav">
                                    <div class="toggle-nav"><i class="fa fa-bars sidebar-bar"></i></div>
                                    <ul id="main-menu" class="sm pixelstrap sm-horizontal">
                                        <li>
                                            <div class="mobile-back text-end">Back<i class="fa fa-angle-right ps-2"
                                                    aria-hidden="true"></i></div>
                                        </li>
                                        <li><a href="{% url 'homepage' %}">ΑΡΧΙΚΗ ΣΕΛΙΔΑ</a></li>
                                        <li>
                                            <a href="#">ΚΑΤΗΓΟΡΙΕΣ</a>
                                            <ul>
                                                {% for category in navbar_categories %}
                                                    <li><a href="{{ category.get_absolute_url }}">{{ category }}</a>
                                                    </li>
                                                {% endfor %}

                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#">ΠΟΛΕΙΣ</a>
                                            <ul>
                                                {% for city in cities %}
                                                    <li><a href="{{ city.get_absolute_url }}">{{ city }}</a>
                                                    </li>
                                                {% endfor %}

                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#">ΠΡΟΪΟΝΤΑ</a>
                                            <ul>
                                                {% for category in product_categories %}
                                                    <li><a href="{{ category.get_absolute_url }}">{{ category }} </a>
                                                    </li>
                                                {% endfor %}

                                            </ul>
                                        </li>

                                        <li><a href="{% url 'service_list_view' %}">ΥΠΗΡΕΣΙΕΣ</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <div>
                                <div class="icon-nav">
                                    <ul>
                                        <li class="onhover-div mobile-search">
                                            <div>
                                                <img src="{% static 'assets/images/icon/search.png' %}" onclick="openSearch()"
                                                    class="img-fluid blur-up lazyload" alt=""> <i class="ti-search"
                                                    onclick="openSearch()"></i>
                                            </div>
                                            <div id="search-overlay" class="search-overlay">
                                                <div> <span class="closebtn" onclick="closeSearch()"
                                                        title="Close Overlay">×</span>
                                                    <div class="overlay-content">
                                                        <div class="container">
                                                            <div class="row">
                                                                <div class="col-xl-12">
                                                                    <form action="{% url 'search' %}">
                                                                        <div class="form-group">
                                                                            <input
                                                                                    type="text"
                                                                                    class="form-control"
                                                                                    name="q"
                                                                                    placeholder="ΑΝΑΖΗΤΗΣΗ"
                                                                                    value='{{ request.GET.q }}'
                                                                            >

                                                                        </div>
                                                                        <button type="submit" class="btn btn-primary"><i
                                                                                class="fa fa-search"></i></button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        {% comment %}
                                        <li class="onhover-div mobile-setting">
                                            <div><img src="../assets/images/icon/setting.png"
                                                    class="img-fluid blur-up lazyload" alt=""> <i
                                                    class="ti-settings"></i></div>
                                            <div class="show-div setting">
                                                <h6>language</h6>
                                                <ul>
                                                    <li><a href="#">english</a></li>
                                                    <li><a href="#">french</a></li>
                                                </ul>
                                                <h6>currency</h6>
                                                <ul class="list-inline">
                                                    <li><a href="#">euro</a></li>
                                                    <li><a href="#">rupees</a></li>
                                                    <li><a href="#">pound</a></li>
                                                    <li><a href="#">doller</a></li>
                                                </ul>
                                            </div>
                                        </li>
                                        {% endcomment %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header end -->